- hosts: maquina1 #Es un server web
  become: true
  roles:
   - role: apache2

- hosts: maquina2 #Es un server bases de datos
  become: true
  roles:
   - role: mariadb

- hosts: all
  become: true
  roles:
   - role: commons
